/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mongodb.Block;
import com.mongodb.client.FindIterable;
import controller.SwimmingCompetition;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import static view.ShowResult.Tmodel;

/**
 *
 * @author prabod
 */
public class ShowResult extends javax.swing.JFrame {

    FindIterable<Document> query;
    static DefaultTableModel Tmodel;

    /**
     * Creates new form ShowResult
     */
    public ShowResult() {
        initComponents();
        query = SwimmingCompetition.db.getResults();
        String[] columnNames = {"Competition", "Results"};
        Tmodel = new DefaultTableModel(columnNames, 0);
        for (Document document : query) {
            String col1 = (String) document.get("comp");
            String[] head = new String[]{
                "Lane", "Name", "Time", "Place"
            };
            JTable results = new JTable();
            DefaultTableModel model1 = new DefaultTableModel(head, 0);
            ArrayList line1 = (ArrayList) document.get("Lane1");
            model1.addRow(line1.toArray());
            ArrayList line2 = (ArrayList) document.get("Lane1");
            model1.addRow(line2.toArray());
            ArrayList line3 = (ArrayList) document.get("Lane1");
            model1.addRow(line3.toArray());
            ArrayList line4 = (ArrayList) document.get("Lane1");
            model1.addRow(line4.toArray());
            ArrayList line5 = (ArrayList) document.get("Lane1");
            model1.addRow(line5.toArray());
            results.setModel(model1);

            JScrollPane tableContainer = new JScrollPane(results);

            jPanel1.add(tableContainer, BorderLayout.CENTER);
            jPanel1.repaint();
            jPanel1.revalidate();
            
            
        }
        
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
